### ISSUE TITLE
关于运行该程序

### ISSUE THREAD

**Issue by runnanzhou** [kastnerorz/animal-crossing-trading-system#2]
作者你好，请问一下我这边根据你的readme跑出来的结果是这样子的，该如何使用呢？谢谢！
<img width="1033" alt="Screen Shot 2020-03-29 at 7 40 23 PM" src="https://user-images.githubusercontent.com/38435730/77870040-39de0800-71f5-11ea-865c-8d5ed1dec363.png">

**Comment by kastnerorz** [comment]
跟路径还没有做映射 访问/login

**Comment by SrvenX-07** [comment]
> 跟路径还没有做映射 访问/login

访问/login也是404，是做了其他什么改动吗？

**Comment by kastnerorz** [comment]
现在映射了，更新一下代码吧
